"""new fields in user model

Revision ID: 5162cbdba256
Revises: 889ce1343d48
Create Date: 2024-02-18 18:19:32.415661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5162cbdba256'
down_revision = '889ce1343d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
