"""new fields in user model

Revision ID: 889ce1343d48
Revises: 74fd6d15a2a5
Create Date: 2024-02-18 18:19:12.660330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '889ce1343d48'
down_revision = '74fd6d15a2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', mysql.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
